# Generated by Django 4.1.5 on 2023-01-28 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_postpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('websiteLink', models.TextField(blank=True, null=True)),
                ('images_directory', models.TextField()),
                ('heads', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
