# Generated by Django 4.1.5 on 2023-01-28 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(related_name='member_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='supervising_faculty',
            field=models.ManyToManyField(related_name='faculty_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='heads',
            field=models.ManyToManyField(related_name='head_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
