# Generated by Django 4.1.5 on 2023-02-03 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_event_lostandfound'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostandfound',
            name='lostDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
