# Generated by Django 4.1.5 on 2023-02-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_lostandfound_lostdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventPicture',
            field=models.ImageField(blank=True, null=True, upload_to='eventPics/'),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='LostAndFoundPics/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postPicture',
            field=models.ImageField(blank=True, null=True, upload_to='postPics/'),
        ),
    ]
