# Generated by Django 4.1.5 on 2023-02-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_lostandfound_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profilePicId',
            field=models.IntegerField(default=1),
        ),
    ]
